Added indexing for dataset and added documentation #89
clowder-framework/clowder2 pull request #109
Opened 2022-09-26 22:24 UTC by ddey2

Signed-off-by: Dipannita Dey <ddey2@illinois.edu>

2022-10-05 14:19 UTC, lmarini requested changes

2022-10-05 22:05 UTC, ddey2 commented on backend/app/config.py
> +    file_settings = {
That makes sense. I will move this settings to elasticsearch's own config file. 

Are you referring to changing the folder name to just 'search' or all the places?

2022-10-05 22:09 UTC, ddey2 commented on backend/app/main.py
>      pass
will remove this.

2022-10-05 22:10 UTC, ddey2 commented on backend/app/routers/files.py
> +    # Add en entry to the file index
Done

2022-10-05 22:11 UTC, ddey2 commented on backend/app/tests/test_elastic_search.py
>  dummy_index_name = "dummy_file"
I was in confusion regarding whether we need a separate test. The reason is I am using the same helper functions for both cases. I have already tested those functions here. 

I can add a different test or rename this to a more generic one.

2022-10-06 14:32 UTC, lmarini commented on backend/app/config.py
> +    file_settings = {
Just the folder name. If you use refactoring it will also fix all the imports.

2022-10-10 19:01 UTC, lmarini commented on backend/app/routers/elasticsearch.py
> +async def update_file(index_name: str, query: str):
Fixed, thank you.

2022-10-10 20:19 UTC, longshuicy approved these changes

2022-10-10 20:23 UTC, lmarini approved these changes

2022-10-10 20:23 UTC, merged