1098 superamin messes up dataset pagination
clowder-framework/clowder2 pull request #1104
Opened 2024-06-10 19:29 UTC by tcnichol

A fix that has worked for me is to make sure that mine=false when using superadmin mode.

2024-06-11 19:22 UTC, lmarini requested changes
- I think this fixes the listed datasets, but the pagination controls seem to have issues. The number of pages is updated, but I don't think a page is selected
- What are the changes to `open.json` for?

2024-06-12 16:40 UTC, tcnichol commented
> * I think this fixes the listed datasets, but the pagination controls seem to have issues. The number of pages is updated, but I don't think a page is selected
> * What are the changes to `open.json` for?

I think open.json got changed when I ran the pre-commit hooks. I can undo that. 

Will check page pagination.

2024-06-24 14:50 UTC, longshuicy requested changes
Admin mode pagination seems to be fixed.
However, in admin mode when I try to switch to "my dataset" tab, it doesn't allow me to flip pages. When I check the network tab I see double calls to the backend: one with mine=true, the other with mine=false.

<img width="594" alt="image" src="https://github.com/clowder-framework/clowder2/assets/13950475/3407d352-4d63-4758-b3a0-997fe97ab82f">

This might related to the logic you added, when adminMode = True you list the dataset with mine=false

```
if (adminMode) {
			listDatasets(0, limit, false);
```
This part.

2024-06-24 18:46 UTC, ddey2 requested changes
Pagination doesn't work on 'My dataset' tab in superadmin mode. 
<img width="1683" alt="Screenshot 2024-06-24 at 1 45 46 PM" src="https://github.com/clowder-framework/clowder2/assets/22405928/ba79755c-faaa-4bc5-a72c-01f341d6f606">

2024-06-24 20:13 UTC, tcnichol commented
> Pagination doesn't work on 'My dataset' tab in superadmin mode. <img alt="Screenshot 2024-06-24 at 1 45 46 PM" width="1683" src="https://private-user-images.githubusercontent.com/22405928/342457169-ba79755c-faaa-4bc5-a72c-01f341d6f606.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTk0NTIsIm5iZiI6MTcxOTI1OTE1MiwicGF0aCI6Ii8yMjQwNTkyOC8zNDI0NTcxNjktYmE3OTc1NWMtZmFhYS00YmM1LWE3MmMtMDFmMzQxZDZmNjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE5NTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZGRhZDg4YzA1ZjE3ZTBmOTQwMTUxYTA2YTBjNzZlZWM2OTFmZWI4NWM5ZWZhZDY4NDk0YjU3YThhZTAwMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i2ibJZbDJe14S8xX7MKq2em9g56Z7-aDa3oOxV4rLgY">

I think I fixed this.

I was not using the current page num in listDatasets, so it was getting stuck at 0 for admin mode and 'mine.' Now when you switch tabs, it changes 'mine' and 'currentPageNum' and then those are used in the hook to populate the datasets.

2024-06-27 14:59 UTC, longshuicy commented
@tcnichol whenever you have a chance could you check if this is resolved with your latest change in the PR? Thanks!! https://github.com/clowder-framework/clowder2/issues/1123

2024-06-27 20:34 UTC, longshuicy commented on frontend/src/components/Explore.tsx
> +			// listDatasets(0, limit, true);
could you remove the inline comment. same as below?

2024-06-27 20:35 UTC, longshuicy approved these changes
This is working correctly now. Also it resovled this issue https://github.com/clowder-framework/clowder2/issues/1123

2024-06-27 21:13 UTC, ddey2 approved these changes
Works perfect.

2024-06-28 14:00 UTC, merged