Download should be incremented as soon as you click on downloads
clowder-framework/clowder2 pull request #1120
Opened 2024-06-21 00:27 UTC by ddey2

2024-06-21 17:16 UTC, tcnichol commented
@ddey2 

I am testing this for datasets and files.

With datasets, when I click the download button the download increments, but the dataset did not download. This happens both on the regular dataset view and the public dataset view.

2024-06-24 14:12 UTC, longshuicy requested changes
I don't think download works. I see it in the network with the binaries; but since you are not catch the binary and save it to blob then generate a tag, the binary is not accessible to end user. 

The public download doesn't work for the same reason.

We used to take similar approach as I described before, but at one point we switch to just embed the url and let the browser handle download due to large files. Not sure if we would like to switch back. Maybe something we can discuss?

2024-06-24 14:12 UTC, longshuicy commented on frontend/src/components/datasets/ActionsMenu.tsx
> +				onClick={() => download(datasetId)}
@lmarini I recall we intentionally changed from the download function to just embed href to handle large file download at a point: https://github.com/clowder-framework/clowder2/pull/692
Do we have to change it back?

2024-06-27 19:27 UTC, ddey2 commented
this is fixed. @tcnichol @longshuicy feel free to take a look

2024-06-27 20:03 UTC, tcnichol commented
Tested.

From the dataset page, every click of download increments. Same for files.

If I download datasets from 'explore' download also increments. Same with downloading files from the filelist.

Marking this one approved.

2024-06-27 20:03 UTC, tcnichol approved these changes
Download increments on datasets and files from any location. Marking this approved.

2024-06-27 20:20 UTC, longshuicy reviewed
Works well. Thanks!

2024-06-27 20:20 UTC, longshuicy approved these changes

2024-06-27 20:20 UTC, merged