290 replace contents in metadata with content
clowder-framework/clowder2 pull request #292
Opened 2023-01-25 18:24 UTC by tcnichol

Testing some extractors I realized the field that was 'content' in v1 was changed to 'contents' in v2, which caused a number of extractors not to work with clowder v2. 

With this pull request I have changed 'contents' to 'content' everywhere, in the back end and front end, hoping that this will reduce the amount of changes that might need to be made to older extractors or in pyclowder. 

Currently wordcount extractors works correctly. 

Other extractor related issues will be taken care of in other pull requests.

2023-01-25 19:26 UTC, longshuicy approved these changes
Pytest is failing again? Besides that looks good. Approved.

2023-01-25 19:29 UTC, tcnichol commented
Fixing pytest, should be done and pushed soon.

2023-02-02 19:30 UTC, max-zilla requested changes
aside from one line that looked duplicated, changes look fine and i didnt notice any issues running things. will approve & merge once removed

2023-02-02 19:30 UTC, max-zilla commented on frontend/src/components/files/UploadFile.tsx
> +				metadata.content = {...prevContent, ...metadata.content};
looks like a duplicate line here

2023-02-03 17:04 UTC, tcnichol commented
I merged main into this one and need to check and make sure it still works.

2023-02-03 22:39 UTC, max-zilla approved these changes

2023-02-03 22:39 UTC, merged