add missing environment variables
clowder-framework/clowder2 pull request #297
Opened 2023-02-01 20:28 UTC by longshuicy

Maybe this will fix the minio issue? How do I redeploy this Helm chart?

2023-02-01 21:34 UTC, robkooper requested changes

2023-02-01 21:34 UTC, robkooper commented on charts/clowder2/templates/backend/deployment.yaml
> +              value: guest
this should not be hardcoded

2023-02-01 21:34 UTC, robkooper commented on charts/clowder2/templates/backend/deployment.yaml
> +            - name: RABBITMQ_PASS
this should not be hardcoded

2023-02-01 21:34 UTC, robkooper commented on charts/clowder2/templates/backend/deployment.yaml
> +              value: minioadmin
this should not be hardcoded

2023-02-01 21:34 UTC, robkooper commented on charts/clowder2/templates/backend/deployment.yaml
> +              value: minioadmin
this should not be hardcoded

2023-02-01 21:34 UTC, robkooper commented on charts/clowder2/templates/backend/deployment.yaml
> +              value: clowder
this should not be hardcoded

2023-02-01 21:34 UTC, robkooper commented on charts/clowder2/templates/backend/deployment.yaml
> +              value: 10 * 1024 * 1024
can we set this in values.yaml?

2023-02-06 21:35 UTC, longshuicy commented on scripts/keycloak/full-kube-clowder-realm-prod.json
> +{
Maybe just keep it here for now until we figure out a more generic way to set this. i.e. pass it in as a file to the helm chart

2023-02-16 15:36 UTC, longshuicy commented
Make sure we limit the Access to IPs within NCSA or UIUC

2023-02-16 15:37 UTC, lmarini approved these changes

2023-02-16 15:39 UTC, merged