Context matches v1 type.
clowder-framework/clowder2 pull request #328
Opened 2023-02-15 23:27 UTC by tcnichol

In clowder v1 context was a list that consisted in URL and dictionary. This pull request makes v2 match v1. Front end and back end have both been changed. Extractor registration should work correctly.

If testing, make sure to remove old metadata/listeners from DB, or else conflicts will happen.

2023-02-16 14:58 UTC, longshuicy commented
Can you fix the linting?

2023-02-16 15:38 UTC, tcnichol commented
To test with extractors, use this branch of pyclowder:

https://github.com/clowder-framework/pyclowder/pull/60

Wordcount and other sample extractors there can be used.

2023-02-16 15:42 UTC, tcnichol commented
For the errors in pytest. These are happening when metadata with no context_url is being posted to the backend for files and datasets. The field is an optional[str] but the validator looks like it throws an error if it is missing. Not sure what to do to fix it. Also that the changes made in this PR shouldn't affect that.

2023-02-21 18:53 UTC, tcnichol commented
@ddey2 I pushed a small change that might fix the errors you are seeing.

2023-02-21 20:29 UTC, ddey2 approved these changes
Looks good, tested.

2023-02-28 14:27 UTC, max-zilla requested changes
everything seemed to work, remove the log and i will merge after tests pass thanks

2023-02-28 14:27 UTC, max-zilla commented on frontend/src/components/metadata/CreateMetadataDefinition.tsx
> +
please remove

2023-02-28 19:38 UTC, tcnichol commented on frontend/src/components/metadata/CreateMetadataDefinition.tsx
> +
removed

2023-03-01 19:15 UTC, merged