348 metadata value not visible on UI
clowder-framework/clowder2 pull request #362
Opened 2023-03-01 20:34 UTC by tcnichol

This should now be fixed for all types. I created metadata definitions that are text input and date, and added the Unit metadata definition to test a dropdown. 

Part of the problem was that 'contents' was used in place of 'content' in a few places so now it's always content for all metadata type. Also fieldName is an object, so using fieldName.name for the key for content[fieldName.name] to get actual metadata value. Metadata can now be created, value shown is right, and the updates work.

2023-03-02 14:53 UTC, ddey2 requested changes
I tried and got Bad request error. No more info on backend. I deleted all the volumes and restarted docker containers, so it shouldn't have nay issue with db as well.


<img width="1703" alt="Screenshot 2023-03-02 at 8 50 58 AM" src="https://user-images.githubusercontent.com/22405928/222462883-6a8d88fd-31a6-49dc-9c52-c5bda154f62e.png">

2023-03-03 19:24 UTC, tcnichol commented
The error should be fixed now.

2023-03-06 16:58 UTC, longshuicy approved these changes

2023-03-06 19:22 UTC, max-zilla approved these changes

2023-03-06 19:23 UTC, merged