WIP 379 GitHub action to run codegen automatically when there is backend change
clowder-framework/clowder2 pull request #396
Opened 2023-03-23 19:16 UTC by longshuicy

Just want to test the github action; not sure if it works

2023-03-28 17:21 UTC, lmarini commented
That endpoint `/broker/{identity_provider}/token` proxies the return of a keycloak call. All our docker file seem to fix the keycloak version to 19.0, but maybe somehow we are running a different version in one case.

2023-03-31 16:13 UTC, longshuicy commented
@lmarini i commented out the `get_idenity_provider_token` and it seems to be consistent now. I reverted the README instruction on how to run codegen. Let me know what else is left on this PR? Thanks~

2023-04-06 14:49 UTC, lmarini requested changes

2023-04-06 14:49 UTC, lmarini commented on backend/app/routers/keycloak.py
> +# def get_idenity_provider_token(
@longshuicy can you add a FIXME here saying we need to parse and return a consistent response? Also can you make an issue for it? I am afraid we will forget. Thank you.

2023-04-06 15:45 UTC, lmarini approved these changes

2023-04-06 15:45 UTC, merged