Fixed the props for search component
clowder-framework/clowder2 pull request #444
Opened 2023-04-19 01:22 UTC by arunapa

* Toggling Advanced switch caused page to break

* Debug logs showed that the properties were not valid, updated code to reflect the same

<img width="1584" alt="image" src="https://user-images.githubusercontent.com/28983148/232942144-b057a784-f986-4940-bbe6-1d611702c9bc.png">

2023-04-19 16:30 UTC, longshuicy requested changes

2023-04-20 14:23 UTC, arunapa commented on frontend/src/components/search/SearchResult.tsx
> -									{parse(item.name)}
@longshuicy I've updated the PR with the try-catch logic, can you try to see if the issue is resolved for you now?

2023-04-21 13:42 UTC, longshuicy commented on frontend/src/components/search/SearchResult.tsx
> -									{parse(item.name)}
Yes it works for me. Approving. Thank you~

2023-04-21 13:42 UTC, longshuicy approved these changes

2023-04-21 15:39 UTC, merged