41 random jwt signature verification failed error
clowder-framework/clowder2 pull request #46
Opened 2022-07-12 18:02 UTC by longshuicy

- Add  Depends(get_current_user) to each protected route. When session expired, `decode_token` still works but `userinfo` will complain about expired signature (suspect related to user session expiration). To unify their behavior, check userinfo 
- Change frontend action to logout user properly when refresh failed. 
- Note don't set the session idle time to a small value. The minimum of those four will decide the life span of refresh token. If set too small this will cause refresh token expiration too soon and can never refresh; and other weird behaviours

![image](https://user-images.githubusercontent.com/13950475/178561617-74a80ec9-ce43-4ddf-a5c3-294c924c15b2.png)

2022-07-13 16:17 UTC, tcnichol approved these changes
Everything seems to work as intended here.

2022-07-18 19:10 UTC, lmarini requested changes

2022-07-20 17:27 UTC, longshuicy commented on frontend/src/components/datasets/CreateDataset.tsx
> +		if (loggedOut) {
done

2022-07-20 17:34 UTC, longshuicy commented
Ready to be reviewed again

2022-08-25 18:50 UTC, lmarini approved these changes

2022-08-25 18:51 UTC, merged