464 public datasets visible to all users
clowder-framework/clowder2 pull request #466
Opened 2023-04-24 21:42 UTC by tcnichol

For this pull request, the following has been implemented.

If a dataset is public, all users can view the dataset, the files, and the metadata. 

A few things I might want to change:

In the route authorization.get_dataset_role, the response type is AuthorizationDB instead of just RoleType (which is the return type for similar methods for file, metadata, etc have.) So for the .get_dataset_role method I create an AuthorizationDB with RoleType 'Viewer' and return that if the dataset is public and the user has no role.

If anybody thinks it would be a better approach, I could change the response type of the .get_dataset_role method to RoleType. That seems like it might make more sense, but I wasn't sure if having the actual authorizationDB object was important anywhere else. 

I have also not figured out a solution for allowing users to view public datasets when not logged in. Thought it would be good to handle this, get some feedback, and then move forward.

2023-04-25 19:53 UTC, tcnichol commented
This one is ready for review.
You can change a dataset to 'public' and all logged in viewers can see a public dataset, the files and metadata. 
Right now these are not visible if not logged in, and 'published' status exists but has no affect yet. Those will be later issues.

2023-04-28 14:17 UTC, longshuicy commented
Based on yesterday's discussion, there seems to be more refactoring needed for this? @tcnichol

2023-04-28 16:48 UTC, tcnichol commented
@longshuicy 

Yes. I'm going to try add new dependencies so that the public datasets will be visible when you are not logged in. So I'll keep working on this one.

I will also change this to draft.

2023-05-22 20:50 UTC, tcnichol commented on frontend/src/routes.tsx
> +import {checkPublic} from "./utils/common"
I took these out. Was trying to get this working for users when they were not logged in, but that was taking too long so I've limited this towards making datasets 'public' for users with accounts. 

I'll handle the other case with another issue.

2023-05-23 13:13 UTC, max-zilla commented
the permissions generally seem to work as expected. however there are still a few buttons public (logged-in) users can see that they don't have permission to use: 
![image](https://github.com/clowder-framework/clowder2/assets/14166971/f5a48b4f-6aa9-41d3-a423-1783d782c4d1)
Can we hide the pencil edit icon and the delete button on the metadata tabs like we did for the Edit buttons for the dataset?

2023-06-09 16:15 UTC, tcnichol commented
> the permissions generally seem to work as expected. however there are still a few buttons public (logged-in) users can see that they don't have permission to use:
> 
> (trying to edit someone else's metadata value) ![image](https://user-images.githubusercontent.com/14166971/240291362-f5a48b4f-6aa9-41d3-a423-1783d782c4d1.png) Can we hide the pencil edit icon and the delete button on the metadata tabs like we did for the Edit buttons for the dataset?

Those buttons should no longer be visible if the user has viewer access only, so no add metadata, delete metadata, or edit.

2023-09-01 14:38 UTC, lmarini requested changes
Playing around with this. A couple of comments:

- I think Public should mean that anyone without an account could see the dataset. To the best of my understanding, right now the implementation makes it so the dataset is viewable to anyone who is logged in.
- When clicking on a file in a dataset that is public but is not shared with the current user, the app throws an error saying resource doesn't exist, which is probably because the file page doesn't respect this new toggle?
- Published is an option, but I don't believe it's being used. We should probably hide it / remove it until we implement it.

2023-10-23 16:48 UTC, lmarini requested changes
Overall looks good to me. A couple of proposed changes:

- [x] When a dataset is public and a user has access to it, they can execute an extractor. I am not sure we want to let them do this. We could disable/hide the button or maybe remove the extract tab all together?
- [ ] I don't think the "Published" option does anything right now. We should deleted from the list of options.

2023-10-31 14:54 UTC, lmarini commented
@tcnichol can fix conflicts? Have you been able to address to the two small changes above? Thanks!

2023-11-01 18:51 UTC, tcnichol commented
> @tcnichol can fix conflicts? Have you been able to address to the two small changes above? Thanks!

I'll be taking care of that this afternoon.

2023-11-01 19:13 UTC, tcnichol commented
Pushed new commits, issues should be resolved and merge conflict fixed.

2023-11-07 17:23 UTC, tcnichol commented
The status is now changed to AUTHENTICATED. The difference will be
AUTHENTICATED means any logged in user can view a dataset, but not someone who is not logged in. PUBLIC datasets can be seen whether you are logged in or not. A separate pull request will implement PUBLIC datasets.

2023-11-13 20:09 UTC, lmarini approved these changes
@tcnichol still works well after changes to label. I made one small change. I moved the submission button to bottom dialog actions in line with other popups and renamed to Update. Please take a look so we are consistent on all popups. Thank you.

2023-11-17 16:56 UTC, merged