Search improvements & bug fixes
clowder-framework/clowder2 pull request #467
Opened 2023-04-25 14:39 UTC by max-zilla

THIS PR CHANGES THE DATASET MODEL from author -> creator, if you see weird errors try deleting your volumes for mongo + elasticsearch and starting with clean db.

Added a ReactiveBase import to the search page that was causing rendering errors. As it is I can use basic and advanced search:
![image](https://user-images.githubusercontent.com/14166971/234312117-fbea3098-f1f3-49ce-8a0a-fd18fb082df2.png)

![image](https://user-images.githubusercontent.com/14166971/234312269-06f853f2-de00-4a03-b391-8b3033f08d95.png)

2023-04-28 13:47 UTC, longshuicy commented
weird after i drop the volumn i see this 
<img width="1737" alt="image" src="https://user-images.githubusercontent.com/13950475/235164976-a22e4df2-a984-48e9-856f-171173e1c90e.png">

I tried to create and add user metadata but it doesn't help. Can anyone else try? Wondering if it's just me

2023-04-28 17:30 UTC, tcnichol commented
@longshuicy what did you put in the search box? i'm trying to replicate the error.

2023-05-01 18:32 UTC, longshuicy reviewed
Will there be any downstream impact of changing "author" to "creator", and "download" to "downloads"? I.e. frontend?

2023-05-01 18:32 UTC, longshuicy commented on backend/app/routers/elasticsearch.py
> +    print(r)
are those prints needed?

2023-05-02 14:01 UTC, max-zilla commented on backend/app/routers/elasticsearch.py
> +    print(r)
no, removed

2023-05-10 13:47 UTC, longshuicy approved these changes

2023-05-10 21:03 UTC, lmarini requested changes
Found one error with renaming datasets.

2023-05-18 18:13 UTC, max-zilla commented on backend/app/models/metadata.py
> -        update_record(es, "metadata", doc, metadata["_id"])
resolved this

2023-05-18 18:28 UTC, lmarini approved these changes

2023-05-18 18:54 UTC, merged