200 fix hardcoding pieces in helm chart
clowder-framework/clowder2 pull request #669
Opened 2023-08-25 15:33 UTC by longshuicy

Load the keycloak realm in as ConfigMap. You can test by deleting the Realm in keycloak and then restart the keycloak pods see if it gets loaded correctly.

2023-08-25 23:11 UTC, robkooper requested changes
This will hard-code the realm to be for a specific instance, and will overwrite the changes that the user makes on a restart of keycloak.

2023-08-25 23:12 UTC, robkooper commented on deployments/kubernetes/charts/clowder2/files/realm.json
This is a massive file, and not sure all the parameters are needed if they are the defaults.

2023-08-28 13:45 UTC, longshuicy commented on deployments/kubernetes/charts/clowder2/files/realm.json
there is a mini version of that but i haven't test it

2023-08-28 13:48 UTC, longshuicy commented
> This will hard-code the realm to be for a specific instance, and will overwrite the changes that the user makes on a restart of keycloak.

Ah right... what's a better way then, using initContainers?

2023-08-28 15:03 UTC, robkooper commented
I would have it as an optional hook (post-install) in the helm chart when you install it (not upgrade). I would have a boolean flag that is "install realm" and have it be false. This way the user can decide that you want to import it.

Problem with init is that if you are not careful it will overwrite any changes the user has made.

2023-08-31 14:33 UTC, longshuicy commented
Created a new task for it #689 for the future.

2023-08-31 18:52 UTC, lmarini approved these changes

2023-08-31 18:52 UTC, merged