Adding admin dependency in authorization of dataset,files, metadata,search
clowder-framework/clowder2 pull request #819
Opened 2023-11-01 18:22 UTC by ddey2

For testing, please use endpoints on Postman as the check is not added to frontend.

2023-11-02 15:26 UTC, ddey2 commented
Hold on to review this one. I need to do some testing.

2023-11-06 19:48 UTC, ddey2 commented on backend/app/tests/test_groups.py
> -    response = client.get(
removed this test as there will always be a role for the admin user.

2023-11-06 19:49 UTC, ddey2 commented on backend/app/tests/test_groups.py
> +    assert response.json().get("role") == "owner"
the admin user role will still be there for the dataset

2023-11-13 19:55 UTC, lmarini requested changes
The line `return DatasetDB.creator.email == current_username.email` at authentication.py:100 is returning `{'creator.email': '<current user email address>'}`  for some reason, which in turn is making all the `if admin` statements true, even if the user is not admin.

2023-11-13 20:45 UTC, ddey2 commented on backend/app/routers/authorization.py
> +    # if admin:
I can't reproduce the issue. 
I created the 1st user and it was automatically assigned the admin. I created 2 datasets.
<img width="1513" alt="Screenshot 2023-11-13 at 2 43 55 PM" src="https://github.com/clowder-framework/clowder2/assets/22405928/4712e534-57f7-4472-8388-bc52da4a8b5d">


I created the 2nd user. I try to login. I can't see any dataset created by the admin,
<img width="1574" alt="Screenshot 2023-11-13 at 2 43 33 PM" src="https://github.com/clowder-framework/clowder2/assets/22405928/015a140c-39a6-45e9-8c62-758602b94895">

2023-11-13 21:40 UTC, ddey2 commented on backend/app/routers/authorization.py
> +    #     return True
done

2023-11-13 21:40 UTC, ddey2 commented on backend/app/routers/authorization.py
> +    # if admin:
I reproduced the bug after an admin user shared the dataset with viewer role with another non-admin user.
Please check now.

2023-11-27 21:19 UTC, tcnichol commented
Question on this one.

I have 2 users in my db right now. One is an admin, and one is not.

If I create a dataset with the non-admin user and upload files, the admin sees the dataset under explore, but when they click the dataset they do not see the files.

But if I download the dataset, they are downloaded.

If I try to access one of the files directly, this error is in the console:

`6565073147e9aeb9a3876b75:1 Access to fetch at 'http://localhost:8000/api/v2/authorizations/files/6565073147e9aeb9a3876b75/role' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

2023-11-30 05:43 UTC, ddey2 commented
@tcnichol Could you check the same issue here in this branch? https://github.com/clowder-framework/clowder2/pull/834
I see that you approved that PR. If we can merge the other one, it should be taken care of in this branch and we can merge it to main then. The super-admin branch contains a lot of other change too on top of this one which takes care of a lot of the functionalities.

2023-11-30 22:07 UTC, longshuicy requested changes
Test a few scenarios all works:
- Admin seeing other person's resources
- Admin search
- Non-Admin see resources only through sharing
- etc

If you fix the merge conflict we can merge :-)

2023-12-01 04:28 UTC, ddey2 commented
> Test a few scenarios all works:
> 
> * Admin seeing other person's resources
> * Admin search
> * Non-Admin see resources only through sharing
> * etc
> 
> If you fix the merge conflict we can merge :-)

done

2023-12-01 15:27 UTC, longshuicy approved these changes

2023-12-01 15:28 UTC, merged