need image tag for heartbeat and listeners
clowder-framework/clowder2 pull request #853
Opened 2023-12-11 22:05 UTC by tcnichol

Without an image tag my local heartbeat and listeners docker images were not being updated, causing issues. 

I found that adding the tags fix the problem, so I added them for these 2 docker images based on what looked like the most current tags. Updated for docker-dev and docker-compose.

2023-12-12 16:44 UTC, lmarini requested changes
Thanks! Let's use `:latest` instead since that is the standard.

2023-12-18 20:15 UTC, tcnichol commented
> Thanks! Let's use `:latest` instead since that is the standard.

Fixed.

2023-12-20 15:14 UTC, lmarini commented on docker-compose.dev.yml
> +    image: "clowder/clowder2-heartbeat:latest"
ok, sorry, let's do that then @tcnichol thank you

2024-01-05 20:33 UTC, tcnichol commented on docker-compose.dev.yml
> +    image: "clowder/clowder2-heartbeat:latest"
I will change it back to main.

2024-01-05 20:40 UTC, ddey2 approved these changes

2024-01-12 15:16 UTC, lmarini approved these changes

2024-01-12 15:16 UTC, merged