hide files pagination on other tabs
clowder-framework/clowder2 pull request #863
Opened 2024-01-08 20:20 UTC by tcnichol

I put this inside a conditional. We just see prev and next for files and then for extractors.

2024-01-08 21:38 UTC, lmarini requested changes
I don't think we need a conditional? If it's just supposed to be in the first TabPanel, can we just move it there? This was probably just a bad merge.

2024-01-09 15:01 UTC, tcnichol commented
> I don't think we need a conditional? If it's just supposed to be in the first TabPanel, can we just move it there? This was probably just a bad merge.

I made the change.

2024-01-12 16:59 UTC, lmarini approved these changes

2024-01-12 21:20 UTC, longshuicy approved these changes
Looks good.

2024-01-12 21:23 UTC, merged